export default function HeatReuseShowcase() {
  return (
    <section className="py-20 px-6 bg-gradient-to-b from-gray-900 to-gray-800 text-white">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            Bitcoin Mining Heat Powers Ultimate Comfort
          </h2>
          <p className="text-xl text-gray-300 max-w-3xl mx-auto">
            Turn waste heat into year-round luxury amenities for your guests
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-8 mb-12">
          <div className="relative overflow-hidden rounded-xl shadow-2xl">
            <img
              src="/assets/banners/winter_hot_tub_bitcoin_heated.png"
              alt="Winter hot tub powered by bitcoin mining heat under Northern Lights"
              className="w-full h-full object-cover"
            />
          </div>

          <div className="flex flex-col justify-center space-y-6">
            <div className="bg-white/10 backdrop-blur-sm p-6 rounded-xl border border-white/20">
              <h3 className="text-2xl font-bold mb-3 text-bitcoin">Year-Round Hot Water</h3>
              <p className="text-gray-200">
                Heat captured from bitcoin miners provides domestic hot water, eliminating traditional water heater costs and energy consumption.
              </p>
            </div>

            <div className="bg-white/10 backdrop-blur-sm p-6 rounded-xl border border-white/20">
              <h3 className="text-2xl font-bold mb-3 text-bitcoin">Spa & Hot Tub Heating</h3>
              <p className="text-gray-200">
                Outdoor hot tubs stay at perfect temperature even in freezing conditions, creating unforgettable guest experiences in mountain winters.
              </p>
            </div>

            <div className="bg-white/10 backdrop-blur-sm p-6 rounded-xl border border-white/20">
              <h3 className="text-2xl font-bold mb-3 text-bitcoin">Radiant Floor Heating</h3>
              <p className="text-gray-200">
                Circulate mining heat through radiant floor systems for ultra-efficient space heating with zero additional energy input.
              </p>
            </div>
          </div>
        </div>

        <div className="bg-white/10 backdrop-blur-sm rounded-xl p-8 border border-white/20">
          <div className="grid md:grid-cols-3 gap-8 text-center">
            <div>
              <div className="text-gray-300 font-bold text-lg mb-2">Heat Capture Efficiency</div>
              <p className="text-sm text-gray-400">
                Immersion cooling systems capture nearly all heat generated by miners
              </p>
            </div>
            <div>
              <div className="text-gray-300 font-bold text-lg mb-2">Continuous Operation</div>
              <p className="text-sm text-gray-400">
                Mining heat available constantly, regardless of weather or season
              </p>
            </div>
            <div>
              <div className="text-gray-300 font-bold text-lg mb-2">Marginal Heating Cost</div>
              <p className="text-sm text-gray-400">
                Free heat as a byproduct of bitcoin earnings transforms economics
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
